"""empty message

Revision ID: 831518d53e05
Revises: 
Create Date: 2019-09-09 15:19:47.317420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831518d53e05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flags_post_id_key', 'flags', type_='unique')
    op.drop_constraint('flags_user_id_key', 'flags', type_='unique')
    op.drop_column('posts', 'flag_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('flag_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_unique_constraint('flags_user_id_key', 'flags', ['user_id'])
    op.create_unique_constraint('flags_post_id_key', 'flags', ['post_id'])
    # ### end Alembic commands ###
